In [14]:
import pandas as pd
import numpy as np
import random

In [15]:
random.seed(10)

In [79]:
citiesnp = np.genfromtxt('cities.csv', delimiter=',', skip_header = 1) 
len(citiesnp)

197769

In [16]:
def createParticle(particleSize, x_min = 0, x_max = 4):
    particle = x_min + (x_max - x_min) * np.random.uniform(low = 0, high = 1, size = particleSize)
    return particle

In [17]:
createParticle(10)

array([0.6691486 , 3.8340455 , 0.39980318, 1.19185106, 1.41762531,
       2.77555999, 1.78757169, 2.28784291, 0.85283191, 1.91563074])

In [18]:
def createParticleVelocities(particleSize, v_min = -4, v_max = 4):
    velocities = v_min + (v_max - v_min) * np.random.uniform(low = 0, high = 1, size = particleSize)
    return velocities

In [19]:
createParticleVelocities(10)

array([-1.47740961, -1.9690734 ,  2.06387171, -3.58127858,  3.38940841,
       -0.63718761,  0.93058317,  2.51372544,  0.12401116, -0.77822969])

In [20]:
def createPopParticles(popSize, particle_length):
    pop = [createParticle(particle_length) for i in range(0,popSize)]
    return pop

In [80]:
citiesnp
pop_test = createPopParticles(5, len(citiesnp))
pop_test

[array([0.137438  , 2.6987953 , 3.71565477, ..., 2.35036192, 2.26725491,
        0.78690851]),
 array([2.26468797, 0.87392239, 2.8220712 , ..., 3.66337268, 3.31174668,
        0.15319971]),
 array([3.11102988, 0.55081829, 2.75535779, ..., 2.41082445, 3.36491434,
        3.23580731]),
 array([0.70589063, 0.57996375, 1.25014984, ..., 0.19973645, 1.19875727,
        1.25863128]),
 array([1.55302532, 2.25822676, 3.00146356, ..., 1.26949811, 2.95233666,
        3.95414013])]

In [23]:
def createPopVelocities(popSize, particle_length):
    pop_vel = [createParticleVelocities(particle_length) for i in range(0,popSize)]
    return pop_vel

In [26]:
pop_vel_test = createPopParticles(5, 10)

In [65]:
def generateSantasPathFromParticlesPop(population):
    path_populations = np.argsort(population).tolist()
    #The constraint is that for each path should start and end at 0!
    for path in path_populations:
        path.remove(0)
        path.insert(0,0)
        path.insert(len(path), 0)
    return path_populations

In [84]:
paths_test = generateSantasPathFromParticlesPop(pop_test)
paths_test[0]

[0,
 8274,
 137093,
 60079,
 162454,
 146246,
 139480,
 70518,
 42155,
 86701,
 179919,
 196948,
 160144,
 158901,
 99845,
 57266,
 175808,
 56222,
 165787,
 182190,
 190851,
 62207,
 70814,
 75375,
 143425,
 6361,
 55532,
 22779,
 66925,
 106689,
 49097,
 28724,
 30641,
 54169,
 101108,
 59300,
 110483,
 116968,
 125906,
 54383,
 28103,
 52263,
 173329,
 74732,
 39134,
 90428,
 110282,
 4716,
 65684,
 194758,
 102780,
 45491,
 182023,
 175296,
 32359,
 116096,
 153672,
 47071,
 73526,
 115282,
 100007,
 191729,
 73983,
 193978,
 132773,
 81524,
 118541,
 29297,
 143216,
 61138,
 183977,
 171216,
 192305,
 41706,
 23630,
 69404,
 6701,
 92449,
 35001,
 88712,
 143283,
 182648,
 62037,
 152997,
 86523,
 162521,
 80601,
 8504,
 19896,
 120293,
 42212,
 122979,
 65161,
 10840,
 160535,
 78840,
 2323,
 184430,
 106361,
 193526,
 8098,
 124547,
 3234,
 21386,
 81408,
 3271,
 176861,
 25853,
 102830,
 64315,
 188122,
 29251,
 80296,
 34503,
 90692,
 104633,
 23874,
 73524,
 113139,
 193308,


In [97]:
import math
def is_prime(n):
    if n == 2:
        return True
    if n % 2 == 0 or n <= 1:
        return False

    sqr = int(math.sqrt(n)) + 1

    for divisor in range(3, sqr, 2):
        if n % divisor == 0:
            return False
    return True
def not_prime(n):
    if n == 2:
        return False
    if n % 2 == 0 or n <= 1:
        return True

    sqr = int(math.sqrt(n)) + 1

    for divisor in range(3, sqr, 2):
        if n % divisor == 0:
            return True
    return False
def cities_distance(cities_path, coors):
    distance = 0
    for index in range(1, len(cities_path)):
        city_a = cities_path[index - 1]
        city_b = cities_path[index]
        a_b_dist = euclidean_dist(city_a, city_b, coors)       
        if ((index % 10 == 0) & (not_prime(city_b))):
            #print("I'm not prime and index multiple of 10!")
            distance = distance + a_b_dist * 1.1 
        else:
            distance = distance + a_b_dist
        #print("Index {}, City {}, a_b_distance: {}, overall_distance: {}".format(index, city_b, a_b_dist, distance))
    return(distance)
def euclidean_dist(id_a, id_b, coors):
    a_coordinates = coors[id_a]
    b_coordinates = coors[id_b]
    partial_sum_X = np.power(a_coordinates[0] - b_coordinates[0], 2)
    partial_sum_Y = np.power(a_coordinates[1] - b_coordinates[1], 2)
    distance = np.sqrt(partial_sum_X + partial_sum_Y)
    return(distance)

In [99]:
distances = []
for path in paths_test:
    distances.append(cities_distance(path, citiesnp))
print(distances)

[13175643383.693033, 13172899051.971361, 13187284357.196564, 13131653453.689054, 13190902514.475733]


In [100]:
def evaluate_paths(paths, cities):
    distances = []
    for path in paths:
        distances.append(cities_distance(path, cities))
    return distances

In [69]:
def particleSwarmOptimization(path_length,
                              cities,
                              ro=10,
                              number_of_iterations = 100,
                              decrement_factor = 0.975,
                              inertia_weight = 0.9,
                              wait_interval = 20):

    #iteration counter
    t = 0
    initial_pop = createPopParticles(popSize= ro, particle_length=n)
    initial_vel = createPopVelocities(popSize= ro, particle_length=n)
    initial_paths = generateSantasPathFromParticlesPop(initial_pop)
    initial_distances = evaluate_paths(initial_paths, cities)

In [33]:
particleSwarm <- function(n, numberOfIterations = 100, decrement_factor = 0.975, inertia_weight = 0.9, wait_interval = 20) {
  # Number of particles to create
  ro = 2 * n
  #iteration counter
  t = 0 
  #Particles
  pop <- createParticlesPopulation(number_of_particles = ro, number_of_jobs =  n)
  # Velocities
  vel <- createParticlesVelocity(number_of_particles = ro, number_of_jobs =  n)
  # Determine job sequences from particles
  job_sequences <- generateJobsFromParticlesPopulation(pop)
  # Compute makespan values for each job sequence
  makespan_particles_values <- evaluatePopulation(job_sequences)
  # store best results and the related iteration in a support matrix
  best_particles_makespan_iteration_matrix <- cbind(job_sequences,
                                               makespan_particles_values$fit,
                                               t)
  job_names <- paste0("Job", 1:n)
  colnames(best_particles_makespan_iteration_matrix) <- c(job_names,
                                                     "best_makespan",
                                                     "best_iteration")
  # Find and store the best particle
  global_best_particle_index <- order(best_particles_makespan_iteration_matrix[, n + 1])[1]
  global_best_particle_params <- best_particles_makespan_iteration_matrix[global_best_particle_index,] # job seq + makespan + iteration
  c1 <- c2 <- 2 # cognitive and social params
  r1 <- runif(1,0,1)
  r2 <- runif(1,0,1)
  for (t in 1:numberOfIterations) {
      
      #Update intertia
      inertia_weight = inertia_weight * decrement_factor
      if (inertia_weight < 0.4) {
        inertia_weight = 0.4
      }
      #update velocity
      vel <- inertia_weight * vel +
        c1 * r1 * (best_particles_makespan_iteration_matrix[,1:n] - pop ) +
        c2 * r2 * (global_best_particle_params[1:n] - pop)
      # update population
      pop <- pop + vel
      #introduce mutation on 10% of pop
      elements_to_mutate <- sample(1:ro, size = ro/10)
      pop[elements_to_mutate, ] <- swapMutation(pop[elements_to_mutate,], n)
      # Obtain the current job sequence from the current particles
      current_jobs <- generateJobsFromParticlesPopulation(pop)
      # Compute makespan for each particle
      current_makespan <- evaluatePopulation(current_jobs)$fit
      # Find which solutions improved during this iteration
      current_sol_is_better_than_previous_one <- current_makespan < best_particles_makespan_iteration_matrix[, n+1]
      # Update the best results matrix
      for (particle in which(current_sol_is_better_than_previous_one)) {
        best_particles_makespan_iteration_matrix[particle,1:n] <- pop[particle, 1:n] #update the particle elements
        best_particles_makespan_iteration_matrix[particle, n+1] <- current_makespan[particle] # update the makespan value
        best_particles_makespan_iteration_matrix[particle, n+2] <- t # update iteration
      }
      # Update global best results
      current_best_particle_index <- order(best_particles_makespan_iteration_matrix[, n + 1])[1]
      current_best_particle_params <- best_particles_makespan_iteration_matrix[current_best_particle_index,]
      if (current_best_particle_params[n + 1] < global_best_particle_params[n + 1]) {
        global_best_particle_params <- current_best_particle_params # update global result
      } else if (global_best_particle_params[n + 2] <= t - wait_interval) {
        break() #no longer improving
      }
       
  }
  res <- cbind(global_best_particle_params, "final_iteration" = t)
  return(res)
  
}

SyntaxError: invalid syntax (<ipython-input-33-9dbfbee95e7a>, line 1)